Repository vaibhavirohilla741/Operationalizing-ML, pull requests merged in 2021-03, with the labels that each got.

#23 update contributing.md
  CONTRIBUTING.md
Labels: GSSoC'21, documentation

#25 Updated README.md
  README.md
Labels: GSSoC'21, documentation

#27 Add Code of Conduct
  CODE_OF_CONDUCT.md
Labels: GSSoC'21, documentation

#29 Update Pull request Template
  .github/pull_request_template.md
Labels: Level 1, documentation, gssoc21

#31 Added License
  LICENSE
  README.md
Labels: Level 2, gssoc21

#34 Update README.md
  README.md
Labels: Level 1, documentation, gssoc21
